version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: portfolio
    volumes:
      - prisma_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://prisma:prisma@db:5432/portfolio
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis

volumes:
  prisma_data: